// Code generated by protoc-gen-go. DO NOT EDIT.
// source: consignment.proto

package go_micro_srv_consignment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
  clien "github.com/micro/go-micro/client"
  server "github.com/micro/go-micro/server"
  context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 货轮承运的一批货物
type Consignment struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Description          string       `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Weight               int32        `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Containers           []*Container `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	VesselId             string       `protobuf:"bytes,5,opt,name=vessel_id,json=vesselId,proto3" json:"vessel_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Consignment) Reset()         { *m = Consignment{} }
func (m *Consignment) String() string { return proto.CompactTextString(m) }
func (*Consignment) ProtoMessage()    {}
func (*Consignment) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{0}
}

func (m *Consignment) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Consignment.Unmarshal(m, b)
}
func (m *Consignment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Consignment.Marshal(b, m, deterministic)
}
func (m *Consignment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Consignment.Merge(m, src)
}
func (m *Consignment) XXX_Size() int {
	return xxx_messageInfo_Consignment.Size(m)
}
func (m *Consignment) XXX_DiscardUnknown() {
	xxx_messageInfo_Consignment.DiscardUnknown(m)
}

var xxx_messageInfo_Consignment proto.InternalMessageInfo

func (m *Consignment) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Consignment) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Consignment) GetWeight() int32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *Consignment) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func (m *Consignment) GetVesselId() string {
	if m != nil {
		return m.VesselId
	}
	return ""
}

// 单个集装箱
type Container struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId           string   `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Origin               string   `protobuf:"bytes,3,opt,name=origin,proto3" json:"origin,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{1}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Container) GetCustomerId() string {
	if m != nil {
		return m.CustomerId
	}
	return ""
}

func (m *Container) GetOrigin() string {
	if m != nil {
		return m.Origin
	}
	return ""
}

func (m *Container) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

// 托运结果
type Response struct {
	Created              bool           `protobuf:"varint,1,opt,name=created,proto3" json:"created,omitempty"`
	Consignment          *Consignment   `protobuf:"bytes,2,opt,name=consignment,proto3" json:"consignment,omitempty"`
	Consignments         []*Consignment `protobuf:"bytes,3,rep,name=consignments,proto3" json:"consignments,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCreated() bool {
	if m != nil {
		return m.Created
	}
	return false
}

func (m *Response) GetConsignment() *Consignment {
	if m != nil {
		return m.Consignment
	}
	return nil
}

func (m *Response) GetConsignments() []*Consignment {
	if m != nil {
		return m.Consignments
	}
	return nil
}

// 查看货物信息的请求
// 客户端想要从服务端请求数据，必须有请求格式，哪怕为空
type GetRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3804bf87090b51a9, []int{3}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Consignment)(nil), "go.micro.srv.consignment.Consignment")
	proto.RegisterType((*Container)(nil), "go.micro.srv.consignment.Container")
	proto.RegisterType((*Response)(nil), "go.micro.srv.consignment.Response")
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.consignment.GetRequest")
}



// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for ShippingService service

type ShippingServiceClient interface {
  // 托运一批货物
  CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error)
  // 查看托运货物的信息
  GetConsignments(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type shippingServiceClient struct {
  c           client.Client
  serviceName string
}

func NewShippingServiceClient(serviceName string, c client.Client) ShippingServiceClient {
  if c == nil {
    c = client.NewClient()
  }
  if len(serviceName) == 0 {
    serviceName = "go.micro.srv.consignment"
  }
  return &shippingServiceClient{
    c:           c,
    serviceName: serviceName,
  }
}

func (c *shippingServiceClient) CreateConsignment(ctx context.Context, in *Consignment, opts ...client.CallOption) (*Response, error) {
  req := c.c.NewRequest(c.serviceName, "ShippingService.CreateConsignment", in)
  out := new(Response)
  err := c.c.Call(ctx, req, out, opts...)
  if err != nil {
    return nil, err
  }
  return out, nil
}

func (c *shippingServiceClient) GetConsignments(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
  req := c.c.NewRequest(c.serviceName, "ShippingService.GetConsignments", in)
  out := new(Response)
  err := c.c.Call(ctx, req, out, opts...)
  if err != nil {
    return nil, err
  }
  return out, nil
}

// Server API for ShippingService service

type ShippingServiceHandler interface {
  // 托运一批货物
  CreateConsignment(context.Context, *Consignment, *Response) error
  // 查看托运货物的信息
  GetConsignments(context.Context, *GetRequest, *Response) error
}

func RegisterShippingServiceHandler(s server.Server, hdlr ShippingServiceHandler, opts ...server.HandlerOption) {
  s.Handle(s.NewHandler(&ShippingService{hdlr}, opts...))
}

type ShippingService struct {
  ShippingServiceHandler
}

func (h *ShippingService) CreateConsignment(ctx context.Context, in *Consignment, out *Response) error {
  return h.ShippingServiceHandler.CreateConsignment(ctx, in, out)
}

func (h *ShippingService) GetConsignments(ctx context.Context, in *GetRequest, out *Response) error {
  return h.ShippingServiceHandler.GetConsignments(ctx, in, out)
}



func init() { proto.RegisterFile("consignment.proto", fileDescriptor_3804bf87090b51a9) }

var fileDescriptor_3804bf87090b51a9 = []byte{
	// 345 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x4d, 0x4e, 0xc3, 0x30,
	0x10, 0x85, 0x49, 0xff, 0x33, 0xa9, 0xa8, 0xea, 0x05, 0x58, 0xb0, 0x20, 0x0a, 0x20, 0x75, 0x95,
	0x45, 0x39, 0x42, 0x16, 0x55, 0xb6, 0xee, 0x1a, 0x41, 0x49, 0x46, 0xe9, 0x48, 0xc4, 0x0e, 0xb6,
	0x5b, 0xae, 0x06, 0xd7, 0xe0, 0x44, 0xa8, 0x49, 0x43, 0x8d, 0x50, 0x51, 0x77, 0x7e, 0x33, 0xfe,
	0xfc, 0xde, 0x58, 0x03, 0xd3, 0x4c, 0x49, 0x43, 0x85, 0x2c, 0x51, 0xda, 0xb8, 0xd2, 0xca, 0x2a,
	0xc6, 0x0b, 0x15, 0x97, 0x94, 0x69, 0x15, 0x1b, 0xbd, 0x8d, 0x9d, 0x7e, 0xf4, 0xe9, 0x41, 0x90,
	0x1c, 0x34, 0x3b, 0x87, 0x0e, 0xe5, 0xdc, 0x0b, 0xbd, 0x99, 0x2f, 0x3a, 0x94, 0xb3, 0x10, 0x82,
	0x1c, 0x4d, 0xa6, 0xa9, 0xb2, 0xa4, 0x24, 0xef, 0xd4, 0x0d, 0xb7, 0xc4, 0x2e, 0x60, 0xf0, 0x8e,
	0x54, 0xac, 0x2d, 0xef, 0x86, 0xde, 0xac, 0x2f, 0xf6, 0x8a, 0x25, 0x00, 0x99, 0x92, 0x76, 0x45,
	0x12, 0xb5, 0xe1, 0xbd, 0xb0, 0x3b, 0x0b, 0xe6, 0xb7, 0xf1, 0xb1, 0x20, 0x71, 0xd2, 0xde, 0x15,
	0x0e, 0xc6, 0xae, 0xc1, 0xdf, 0xa2, 0x31, 0xf8, 0xfa, 0x44, 0x39, 0xef, 0xd7, 0xe6, 0xa3, 0xa6,
	0x90, 0xe6, 0x51, 0x09, 0xfe, 0x0f, 0xf5, 0x27, 0xf8, 0x0d, 0x04, 0xd9, 0xc6, 0x58, 0x55, 0xa2,
	0xde, 0xb1, 0x4d, 0x70, 0x68, 0x4b, 0x69, 0xbe, 0xcb, 0xad, 0x34, 0x15, 0x24, 0xeb, 0xdc, 0xbe,
	0xd8, 0x2b, 0x76, 0x09, 0xc3, 0x8d, 0x69, 0xa0, 0x5e, 0xd3, 0xd8, 0xc9, 0x34, 0x8f, 0x3e, 0x3c,
	0x18, 0x09, 0x34, 0x95, 0x92, 0x06, 0x19, 0x87, 0x61, 0xa6, 0x71, 0x65, 0xb1, 0xf1, 0x1c, 0x89,
	0x56, 0xb2, 0x05, 0x04, 0xce, 0x5c, 0xb5, 0x71, 0x30, 0xbf, 0xff, 0x77, 0xf0, 0xf6, 0x2c, 0x5c,
	0x92, 0xa5, 0x30, 0x76, 0xa4, 0xe1, 0xdd, 0xfa, 0x0b, 0x4f, 0x7c, 0xe9, 0x17, 0x1a, 0x8d, 0x01,
	0x16, 0x68, 0x05, 0xbe, 0x6d, 0xd0, 0xd8, 0xf9, 0x97, 0x07, 0x93, 0xe5, 0x9a, 0xaa, 0x8a, 0x64,
	0xb1, 0x44, 0xbd, 0xa5, 0x0c, 0xd9, 0x33, 0x4c, 0x93, 0x7a, 0x00, 0x77, 0x19, 0x4e, 0xf3, 0xba,
	0x8a, 0x8e, 0x5f, 0x6b, 0xff, 0x2b, 0x3a, 0x63, 0x8f, 0x30, 0x59, 0xa0, 0x75, 0x38, 0xc3, 0xee,
	0x8e, 0x83, 0x87, 0xb8, 0xa7, 0x3d, 0xff, 0x32, 0xa8, 0x37, 0xfd, 0xe1, 0x3b, 0x00, 0x00, 0xff,
	0xff, 0x71, 0x44, 0xa7, 0xc3, 0xfe, 0x02, 0x00, 0x00,
}
